name: workflow-main
on:
  push:
    branches:
      - "main"
jobs:
  job-main:
    runs-on: ubuntu-latest
    steps:
    - name: "step-checkout"
      uses: actions/checkout@v1
    - name: "step-log"
      run: |
        echo "[B] github.ref: ${{github.ref}}"
