name: workflow-tags
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  job-tags:
    runs-on: ubuntu-latest
    steps:
    - name: "step-checkout"
      uses: actions/checkout@v1
    - name: "step-log"
      run: |
        echo "[C] github.ref: ${{github.ref}}"
